ancient_civilization_hub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('ancient_civilizations_hub.urls')),
]

ancient_civilizations_hub/urls.py
"""Defines URL patterns for ancient_civilizations_hub."""

from django.urls import path

from . import views

app_name = 'ancient_civilizations_hub'
urlpatterns = [
        # Home Page
        path('', views.index, name='index'),
        # Page that shows all civilizations.
        path('civilizations/', views.civilizations, name='civilizations'),
        # Detail page for a single civilization. 
        path('civilizations/<int:civilization_id>/', views.civilization, name='civilization'),
        # Page for adding a new civilization
        path('new_civilization/', views.new_civilization, name='new_civilization'),
        # Page for adding a new entry
        path('new_civilization/<int:civilization_id>/', views.new_entry, name='new_entry'),
        # Page for editing an entry.
        path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]
  

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

ancient_civilizations_hub/models.py
from django.db import models
from django.contrib.auth.models import User

class Civilization(models.Model):
    """A Civilization the user is learning about."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text


class Entry(models.Model):
    """Something specific learned about a Civilization"""
    civilization = models.ForeignKey(Civilization, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model"""
        return f"{self.text[:50]}..."

users/models.py
from django.db import models

# Create your models here.

ancient_civilizations_hub/forms.py
from django import forms 

from .models import Civilization, Entry

class CivilizationForm(forms.ModelForm):
    class Meta:
        model = Civilization
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

ancient_civilizations_hub/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Civilization, Entry
from .forms import CivilizationForm, EntryForm

def index(request):
    """The home page for Ancient Civilization Hub."""
    return render(request, 'ancient_civilizations_hub/index.html')

@login_required
def civilizations(request):
    """Show all civilizations."""
    civilizations = Civilization.objects.filter(owner=request.user).order_by('date_added')
    context = {'civilizations': civilizations}
    return render(request, 'ancient_civilizations_hub/civilizations.html', context)

@login_required
def civilization(request, civilization_id):
    """Show a single civilization and all its entries."""
    civilization = Civilization.objects.get(id=civilization_id)
    civilization = get_object_or_404(Civilization, id=civilization_id)
    # Make sure the civilization belongs to the current user.
    if civilization.owner != request.user:
        raise Http404


    entries = civilization.entry_set.order_by('-date_added')
    context = {'civilization': civilization, 'entries': entries}
    return render(request, 'ancient_civilizations_hub/civilization.html', context)


@login_required
def new_civilization(request):
    """Add a new civilization."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = CivilizationForm
    else:
        # POST data submitted; process data.
        form = CivilizationForm(data=request.POST)
        if form.is_valid():
            new_civilization = form.save(commit=False)
            new_civilization.owner = request.user
            new_civilization.save()
            return redirect('ancient_civilizations_hub:civilizations')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'ancient_civilizations_hub/new_civilization.html', context) 


@login_required
def new_entry(request, civilization_id):
    """Add a new entry for a particular civilization."""
    civilization = Civilization.objects.get(id=civilization_id)

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.civilization = civilization
            new_entry.save()
            return redirect('ancient_civilizations_hub:civilization', civilization_id=civilization_id)
        
    # Display a blank or invalid form.
    context = {'civilization': civilization, 'form': form}
    return render(request, 'ancient_civilizations_hub/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    civilization = entry.civilization
    if civilization.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # Post data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():       
            form.save()
            return redirect('ancient_civilizations_hub:civilization', civilization_id=civilization.id)        
        
    context = {'entry': entry, 'civilization': civilization, 'form': form}
    return render(request, 'ancient_civilizations_hub/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('ancient_civilizations_hub:index')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

ancient_civilizations_hub/templates/ancient_civilizations_hub/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content=""width=device-width, initial-scale=1,
        shrink-to-fit="no">
    <title>Ancient Civilization Hub</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

  </head>

  <body>
    
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

      <a class="navbar-brand" href="{url 'ancient_civilizations_hub:index' %}">
          Ancient Civilization Hub</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
<div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'ancient_civilizations_hub:civilizations'%}">
          Civilizations</a></li>
</ul>
<ul class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <span class="nav-item">
            <span class="navbar-text">Hello, {{ user.username }}.</span>
        </li>
        <li class="nav-item">
          <a  class="nav-link" href="{% url 'users:logout' %}"> Log out</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
      {% endif %}
    </ul>
  </div>
</nav>

  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>
</body>
</html>
    

ancient_civilizations_hub/templates/ancient_civilizations_hub/civilization.html
{% extends 'ancient_civilizations_hub/base.html' %} 
 
{% block page_header %}
    <h3>{{ civilization }}</h3>
{% endblock page_header %}


{% block content %}

<p>Civilization: {{ civilization }}</p>

<p>Entries:</p>
<p>
    <a href="{% url 'ancient_civilizations_hub:new_entry' civilization.id %}">Add new entry</a>
</p>
<ul>
{% for entry in entries %}
    <div class="card mb-3">
        <h4 class="card-header">
            {{ entry.date_added|date:'M d, Y H:i' }}
            <small><a href="{% url 'ancient_civilizations_hub:edit_entry' entry.id %}">
                edit entry</a></small>
        </h4>
    <div class="card-body">
        {{ entry.text|linebreaks }}
    </div>
    </div>
{% empty %}
    <p>There are no entries for this civilization yet.</p>
{% endfor %}
{% endblock content %}

ancient_civilizations_hub/templates/ancient_civilizations_hub/civilizations.html
{% extends "ancient_civilizations_hub/base.html" %}

{% block page_header %}
    <h1>Civilizations</h1>
{% endblock page_header %}

{% block content %}
    <ul>
        {% for civilization in civilizations %}
            <li><h3>
              <a href="{% url 'ancient_civilizations_hub:civilization' civilization.id %}"> {{ civilization }}</a>
            </h3></li>
        {% empty %}
            <li><h3>No Civilizations have been added yet.</h3></li>
        {% endfor %}
    </ul>
    

    <h3><a href ="{% url 'ancient_civilizations_hub:new_civilization' %}">Add a new civilization</a></h3>
{% endblock content %}

ancient_civilizations_hub/templates/ancient_civilizations_hub/edit_entry.html
{% extends "ancient_civilizations_hub/base.html" %}

{% block content %}

<p><a href="{% url 'ancient_civilizations_hub:civilization' civilization.id %}">{{ civilization }}</a></p>

<p>Edit entry:</p>

<form action="{% url 'ancient_civilizations_hub:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save changes</button>
    </form>

{% endblock content %}

ancient_civilizations_hub/templates/ancient_civilizations_hub/index.html
{% extends "ancient_civilizations_hub/base.html" %}

{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-3">View Your Ancient Civilizations.</h1>

        <p class="lead">Make a learning hub for Ancient Civilizations, and keep a list
            of the civilizations you have gained knowledge on. Whenever you learn 
            something new about a civilization, make an entry summarizing what you have
            learned.</p>


        <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
            role="button">Register &raquo;</a>

    </div>
{% endblock page_header %}

ancient_civilizations_hub/templates/ancient_civilizations_hub/new_civilization.html
{% extends "ancient_civilizations_hub/base.html" %}

{% block content %}
  <p>Add a new civilization:</p>

<form action="{% url 'ancient_civilizations_hub:new_civilization' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add civilization</button>
    </form>

{% endblock content %}

ancient_civilizations_hub/templates/ancient_civilizations_hub/new_entry.html
{% extends "ancient_civilizations_hub/base.html" %}

{% block content %}

<p><a href="{% url 'ancient_civilizations_hub:civilization' civilization.id %}">{{ civilization }}</a></p>

<p>Add a new entry:</p>
<form action="{% url 'ancient_civilizations_hub:new_entry' civilization.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add entry</button>
    </form>

{% endblock content %}